INPUT:
  BRIGHTNESS: 0.0
  CONTRAST: 0.0
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  HUE: 0.0
  MAX_SIZE_TEST: 1524
  MAX_SIZE_TRAIN: 1524
  MIN_SIZE_TEST: 1464
  MIN_SIZE_TRAIN: (1400,1432,1464)
  ROTATE_PROB_TRAIN: 0.0
  SATURATION: 0.0
  TO_BGR255: true
  VERTICAL_FLIP_PROB_TRAIN: 0.0

MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  ROTATED: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    PRE_NMS_TOP_N_TEST: 2000
    POST_NMS_TOP_N_TEST: 300

    PRE_NMS_TOP_N_TRAIN: 4000
    PRE_NMS_TOP_N_TRAIN: 1000

    STRADDLE_THRESH: -1
    ANCHOR_ANGLES: (-90,-60,-30)
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    NMS_THRESH: 0.5 # 0.7
    #ANCHOR_SIZES: (32, 64, 128, 512)
    ASPECT_RATIOS: (0.25, 0.5 ,1.0 ,2.0, 4.0)
    BBOX_REG_WEIGHTS: (1.0, 1.0, 1.0, 1.0, 1.0)
    USE_FPN: True

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    
  ROI_HEADS:
    USE_FPN: True
    FG_IOU_THRESHOLD: 0.5
    NMS: 0.5
    # weights on (dx, dy, dw, dh, dtheta) for normalizing rotated rect regression targets
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0, 1.0)
    
DATASETS:
  TRAIN: ("CVD_baseline_cluster_train",)
  TEST: ("CVD_baseline_cluster_val",)

DATALOADER:
  NUM_WORKERS: 0
  SIZE_DIVISIBILITY: 32
#OUTPUT_DIR: data/rotated_maskrcnn/checkpoints/rotated/cvd_2
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (2000,)
  MAX_ITER: 2500
  IMS_PER_BATCH: 1
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear

TEST: 
  IMS_PER_BATCH: 1