MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  ROTATED: True
  RPN_ONLY: True
  RPN:
    PRE_NMS_TOP_N_TEST: 12000
    POST_NMS_TOP_N_TEST: 2000

    ANCHOR_ANGLES: (-90, -60, -30)
    STRADDLE_THRESH: -1
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
